using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace CMCS.Helpers
{
    public static class SessionExtensions
    {
        // code were generated by AI, but under AI guide and brainstorm for understanding purpose
        // this code is used to convert session objects into JSON string and back to object
        // example usage: session.SetObject("api-name", viewmodel ... etc)
        // this is mainly for storing temporary ViewModel or complex data in Session
        // AI recommended this as a convenient way for handling complex session data
        // however for authentication, using UserId and Role with
        // "HttpContext.Session.SetInt32(...)" is simpler, safer and considered as more suitable
        public static void SetObject<T>(this ISession session, string key, T value)
        {
            // read json value(string...etc)
            session.SetString(key, JsonSerializer.Serialize(value));
        }

        public static T GetObject<T>(this ISession session, string key)
        {
            //to get object of the json api
            var value = session.GetString(key);
            return value == null ? default : JsonSerializer.Deserialize<T>(value);
        }
    }
}
