using CMCS.Models;
using System.Collections.Generic;
using System.Reflection.Emit;
using Microsoft.EntityFrameworkCore;

namespace CMCS.Data
{
    //most of the code been checked and efficiency by the Chatgpt, original code was brainstorm and gide by the chat gpt, few methods generated by AI
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
        public DbSet<Claim> Claims { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // model builder were generated ,but under AI guid and brainstorm for explain the purpose
            base.OnModelCreating(modelBuilder);

            // Claim Lecturer
            modelBuilder.Entity<Claim>()
                .HasOne(c => c.Lecturer)
                .WithMany()
                .HasForeignKey(c => c.LecturerID)
                .OnDelete(DeleteBehavior.Restrict);

            // Claim User
            modelBuilder.Entity<Claim>()
                .HasOne(c => c.User)
                .WithMany(u => u.Claims)
                .HasForeignKey(c => c.UserID)
                .OnDelete(DeleteBehavior.Cascade);


            modelBuilder.Entity<User>().HasData(
                //add HR
        new User
        {
            Id = 1,
            UserCode = "HR",
            Username = "HR",
            Password = "0000",
            Role = "HR",
            Email = "hr@gmail.com",
            ContactNumber = "1234567890"
        }
    );
        }
    }
}
